2019-11-26 23:21:45.485 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:400...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:21:45.519 [error] <0.288.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.449.0>,1,<0.450.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:23:39.337 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,path => <<"/">>,path_info => undefined,peer => {{127,0,0,1},56294},pid => <0.448.0>,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:23:39.358 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,1,<0.449.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,...}},...},...},...},...},...]},...}}
2019-11-26 23:23:50.010 [error] <0.453.0> CRASH REPORT Process <0.453.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,path => <<"/api/">>,path_info => undefined,peer => {{127,0,0,1},56296},pid => <0.452.0>,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:23:50.013 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.452.0>,1,<0.453.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,...}},...},...},...},...},...]},...}}
2019-11-26 23:24:00.209 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:400...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:00.212 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.456.0>,1,<0.457.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:24:24.460 [error] <0.461.0> CRASH REPORT Process <0.461.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => ...,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:24.464 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.460.0>,1,<0.461.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:24:26.320 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => ...,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:26.323 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.464.0>,1,<0.465.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:24:52.982 [error] <0.469.0> CRASH REPORT Process <0.469.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:52.984 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.468.0>,1,<0.469.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:24:55.345 [error] <0.473.0> CRASH REPORT Process <0.473.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:55.348 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.472.0>,1,<0.473.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:25:06.680 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:400...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:06.684 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.476.0>,1,<0.477.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:25:28.201 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:28.236 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,1,<0.449.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:25:29.056 [error] <0.454.0> CRASH REPORT Process <0.454.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:29.059 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.453.0>,1,<0.454.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:25:30.180 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:30.183 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.453.0>,2,<0.457.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:26:22.595 [error] <0.455.0> CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"keep-...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:22.635 [error] <0.296.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.454.0>,1,<0.455.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:26:24.257 [error] <0.460.0> CRASH REPORT Process <0.460.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"keep-...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:24.260 [error] <0.296.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.459.0>,1,<0.460.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:26:41.105 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,2,[{file,"lib/toy_..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:41.130 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,1,<0.449.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',...},...]},...},...]},...}}
2019-11-26 23:26:42.677 [error] <0.452.0> CRASH REPORT Process <0.452.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,2,[{file,"lib/toy_..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:42.679 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,2,<0.452.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',...},...]},...},...]},...}}
2019-11-26 23:30:19.192 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:30:19.214 [error] <0.286.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.444.0>,1,<0.445.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers..."},...]},...]},...},...]},...}}
2019-11-26 23:30:21.170 [error] <0.448.0> CRASH REPORT Process <0.448.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:30:21.172 [error] <0.286.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.444.0>,2,<0.448.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers..."},...]},...]},...},...]},...}}
